# Generated by Django 6.0 on 2026-01-06 04:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineEncryptedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('encrypted_data', models.BinaryField()),
                ('encryption_key', models.BinaryField()),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_encrypted', to='transfers.uploadsession')),
            ],
        ),
    ]
