# Generated by Django 6.0 on 2026-01-08 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_onlineencryptedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineencryptedfile',
            name='encryption_key',
        ),
    ]
