# Generated by Django 6.0 on 2026-01-12 04:59

import transfers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0004_remove_onlineencryptedfile_encryption_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineencryptedfile',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='onlineencryptedfile',
            name='expires_at',
            field=models.DateTimeField(default=transfers.models.default_expiry),
        ),
    ]
