# Generated by Django 6.0 on 2026-01-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0005_onlineencryptedfile_download_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineencryptedfile',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='onlineencryptedfile',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
