# Generated by Django 6.0 on 2026-01-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0006_onlineencryptedfile_failed_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineencryptedfile',
            name='allowed_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlineencryptedfile',
            name='enable_ip_lock',
            field=models.BooleanField(default=False),
        ),
    ]
