# Generated by Django 6.0 on 2026-01-12 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0007_onlineencryptedfile_allowed_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='transfers.onlineencryptedfile')),
            ],
        ),
    ]
