# Generated by Django 6.0 on 2026-02-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0010_downloadaudit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineencryptedfile',
            name='max_downloads',
            field=models.IntegerField(default=3),
        ),
    ]
