# Generated by Django 6.0 on 2026-02-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0011_onlineencryptedfile_max_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineencryptedfile',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='onlineencryptedfile',
            name='encrypted_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
