# Generated by Django 6.0 on 2026-02-05 06:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0012_add_supabase_storage_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='chunk_data',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='chunk_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='total_chunks',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='transfers.uploadsession'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OfflineJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_chunks', models.IntegerField(default=0)),
                ('processed_chunks', models.IntegerField(default=0)),
                ('result_file', models.BinaryField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offline_job', to='transfers.uploadsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
