# Generated by Django 5.1.15 on 2026-03-16 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0014_contactmessage_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='downloadaudit',
            index=models.Index(fields=['-timestamp'], name='transfers_d_timesta_de5b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadaudit',
            index=models.Index(fields=['file', '-timestamp'], name='transfers_d_file_id_f01de2_idx'),
        ),
        migrations.AddIndex(
            model_name='offlinejob',
            index=models.Index(fields=['user', 'status', '-created_at'], name='transfers_o_user_id_5caec6_idx'),
        ),
        migrations.AddIndex(
            model_name='offlinejob',
            index=models.Index(fields=['status', 'created_at'], name='transfers_o_status_654083_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineencryptedfile',
            index=models.Index(fields=['token'], name='transfers_o_token_4f806f_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineencryptedfile',
            index=models.Index(fields=['expires_at'], name='transfers_o_expires_a32e86_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineencryptedfile',
            index=models.Index(fields=['-uploaded_at'], name='transfers_o_uploade_27fb99_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['user', 'is_active', 'created_at'], name='transfers_u_user_id_a98fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['-created_at'], name='transfers_u_created_740738_idx'),
        ),
    ]
